/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AwesomeWrap {
    }
}
declare global {
    interface HTMLAwesomeWrapElement extends Components.AwesomeWrap, HTMLStencilElement {
    }
    var HTMLAwesomeWrapElement: {
        prototype: HTMLAwesomeWrapElement;
        new (): HTMLAwesomeWrapElement;
    };
    interface HTMLElementTagNameMap {
        "awesome-wrap": HTMLAwesomeWrapElement;
    }
}
declare namespace LocalJSX {
    interface AwesomeWrap {
    }
    interface IntrinsicElements {
        "awesome-wrap": AwesomeWrap;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "awesome-wrap": LocalJSX.AwesomeWrap & JSXBase.HTMLAttributes<HTMLAwesomeWrapElement>;
        }
    }
}
